# Generated by Django 5.2 on 2025-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringservice',
            name='activity',
            field=models.TextField(),
        ),
    ]
